### ISSUE TITLE
Native try catch support

### ISSUE THREAD

**Issue by koculu** [ClearFoundry/ClearScript#301]
ClearScript provides a separate function for error handling.

https://microsoft.github.io/ClearScript/Reference/html/M_Microsoft_ClearScript_HostFunctions_tryCatch.htm

It would be nice if we can use javascript try catch too.
Currently try catch blocks gets a Microsoft.ClearScript.V8.V8ScriptItem.

Would it be easy to implement such feature?

Suggested use case:
```
// C#
public void Foo() {
  throw new Exception("foo exception")
}
// javascript usage
try { 
   Foo()
} catch(err) {
  console.log(err) // output: foo exception
  console.log(err.ActualException) // output System.Exception object
}
```

**Comment by ClearScriptLib** [comment]
HI @koculu,

If you're using V8, you can already do this. For example, given the `Foo` above, you can do this:

``` C#
engine.Script.Foo = new Action(Foo);
engine.AddHostType(typeof(Console));
engine.Execute(@"
    try {
        Foo();
    }
    catch (err) {
        Console.WriteLine(err.toString());
        Console.WriteLine(err.hostException.GetBaseException());
    }
");
```

We provide `HostFunctions.tryCatch` for script engines that (a) don't provide sufficient hooks to enable the above (e.g., JScript), or (b) implement languages that don't support exceptions at all (e.g., VBScript).

Good luck!
